library_name := playlist_ui
dirs.root := ../../../..

source_dirs := .

ui_files := container_view scanner_view
moc_files := playlist_view table_view uiproxymodel uiproxymodel_p

ts_files := playlist_ui

include $(dirs.root)/makefile.mak
